In [1]:
import numpy as np
import math

In [ ]:
###  ### 

In [12]:
### 3.checkPalindrome ### 
inputString = 'aabaa'
a = len(inputString)%2
print(a)
b = int((len(inputString)-a)/2)
print(b)
head = inputString[:b]
print(head)
tail = inputString[b+a:][::-1]
print(tail)
head == tail

1
2
aa
aa


True

In [3]:
### 4.adjacentElementsProduct ### 
inputArray = [3, 6, -2, -5, 7, 3]
a=inputArray[:-1]
b=inputArray[1:]
print(a)
print(b)
prod = []
for i in range(len(a)):
    prod.append(a[i]*b[i])
print(prod)
max(prod)

[3, 6, -2, -5, 7]
[6, -2, -5, 7, 3]
[18, -12, 10, -35, 21]


21

In [4]:
### 5.shapeArea ### 
n=4
a=1
g=[1]
for i in range(n-1):
    a=(a+2)
    g.append(a)
print(g)
print(g[:-1][::-1])
sum(g[:-1][::-1])+sum(g)

[1, 3, 5, 7]
[5, 3, 1]


25

In [11]:
### 6.Make Array Consecutive2 ### 
statues = [6, 2, 3, 8]
total = np.arange(min(statues),max(statues)+1,1).tolist()
len(set(total)-set(statues))

3

In [10]:
### 7.almostIncreasingSequence ### 
sequence = [1,3,2]
n = len(sequence)
if n <= 2:
    # return True
    print('TRUE')
c1 = 0
c2 = 0    
for i in range(1, n-1):
    if sequence[i-1] >= sequence[i]:
        c1 += 1
    if sequence[i-1] >= sequence[i+1]:
        c2 += 1
if sequence[n-1] <= sequence[n-2]:
    c1 += 1
if c1 <= 1 and c2 <= 1:
    # return True
    print('TRUE')
else:
    # return False
    print('False')

TRUE


In [13]:
### 8.matrixElementSum ### 
matrix = [[0, 1, 1, 2], 
          [0, 5, 0, 0], 
          [2, 0, 3, 3]]
m = np.array(matrix).transpose()
print(m)
b=[]
for i in m:
    a =0
    for j in i:
        if j==0:
            break
        else: a+=j
    b.append(a)
sum(b)

[[0 0 2]
 [1 5 0]
 [1 0 3]
 [2 0 3]]


9

In [9]:
### 9.All Longest Strings ### 
inputArray = ["aba", "aa", "ad", "vcd", "aba"]
a = [len(i) for i in inputArray]
m = max(a)
output = []
for i in range(len(a)):
    if a[i]==m:
        output.append(inputArray[i])
output

['aba', 'vcd', 'aba']

In [25]:
### 10.commonCharacterCount ### 交集
s1 = "aabcc"
s2 = "adcaa"
# print(set(s1).intersection(set(s2)))
c=0
for i in s1:
    print(i)
    if i in s2:
        c+=1
        s2 = s2.replace(i,'',1)
        print(s2)
c

a
dcaa
a
dca
b
c
da
c


3