In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/Users/nicolelinmbp2022/venv/lib/python3.9/site-packages/numpy/__init__.py'>
1.23.4


In [7]:
# generate array
print(np.arange(4))
print(np.arange(2,10,3))

[0 1 2 3]
[2 5 8]


In [12]:
# 相同大小的陣列運算
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print('a: ', a)
print('b: ', b)
print('a+b:', a + b)
print('a+b:', a * b)
print('a+1: ', a+1)
print('a>b:', a > b)


a:  [20 30 40 50]
b:  [0 1 2 3]
a+b: [20 31 42 53]
a+b: [  0  30  80 150]
a+1:  [21 31 41 51]
a>b: [ True  True  True  True]


In [11]:
# 不同大小的陣列運算

import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
# IF ones_row = np.array([[1, 1, 1]]) 則會Error
print('data:', data)
print('ones_row:', ones_row)
print('data + ones_row:', data + ones_row)

data: [[1 2]
 [3 4]
 [5 6]]
ones_row: [[1 1]]
data + ones_row: [[2 3]
 [4 5]
 [6 7]]


In [14]:
a = np.array( [True, True, False, False] )
b = np.array( [True, False, True, False]  )

# print(a and b) # 無法使用
print(a & b) # [ True False False False]
print(a | b) # [ True  True  True False]


[ True False False False]
[ True  True  True False]


In [26]:
a = np.arange(12)
print(a)
print(a.reshape(2, 6))

print(a.resize(2, 6))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
None
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [17]:
a = np.random.randint(1, 20, 10)
print(a)
print(a.max())
print(np.amax(a))
print(a.argmax()) #回傳位置

print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

[ 5  4  6 12 10  8  7 17 11 18]
18
18
9
98
98
98


In [28]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a))
print(np.bincount(a).argmax()) #找出出現最多次的數字
print(np.sort(a))


[1 2 4 6 5 1 9 6 8 2 6 4 3 6 7 1 3 9 9 1 3 6 8 0 9 7 3 4 2 7 0 1 0 5 7 1 0
 2 7 7 4 4 2 6 7 7 3 7 7 0]
[ 5  6  5  5  5  2  6 10  2  4]
7
[0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 6 6 6 6 6 6 7 7 7
 7 7 7 7 7 7 7 8 8 9 9 9 9]
[1 2 4 6 5 1 9 6 8 2 6 4 3 6 7 1 3 9 9 1 3 6 8 0 9 7 3 4 2 7 0 1 0 5 7 1 0
 2 7 7 4 4 2 6 7 7 3 7 7 0]


In [21]:
b = np.arange(12).reshape(3, 4)

print('b:', b)
print('全部相加：', b.sum())
print('直行相加：', b.sum(axis=0))
print('橫列相加：', b.sum(axis=1))


b: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
全部相加： 66
直行相加： [12 15 18 21]
橫列相加： [ 6 22 38]
